'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Store, Plus, ClipboardList, BriefcaseBusiness, UserCheck, CircleCheck, ChevronDown, ChevronUp, Pencil } from 'lucide-react';
import { useApp } from '@/lib/store';
import { BUSINESS_ID } from '@/lib/data';
import { dateLabel } from '@/lib/utils';
import { statusLabels } from '@/lib/status';
import { JobLogo } from '@/components/job-card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
export default function BusinessPage() {
 const { jobs, applications, ready, remaining, applicantCount, updateApplication } = useApp(); const [expanded, setExpanded] = useState<string | null>(null); const mine = jobs.filter(j => j.ownerId === BUSINESS_ID); const relevant = applications.filter(a => mine.some(j => j.id === a.jobId));
 const thisMonth = new Date();
 const stats = [{ label: '待审核报名', value: relevant.filter(a => a.status === 'pending').length, icon: ClipboardList, note: '期待你的回复' },{ label: '招聘中的兼职', value: mine.filter(j => remaining(j) > 0).length, icon: BriefcaseBusiness, note: '好帮手就在附近' },{ label: '已确认兼职', value: relevant.filter(a => a.status === 'confirmed').length, icon: UserCheck, note: '记得安排到岗' },{ label: '本月完成兼职', value: relevant.filter(a => { const job = mine.find(j => j.id === a.jobId); const date = new Date(`${job?.date}T12:00:00`); return a.status === 'completed' && date.getFullYear() === thisMonth.getFullYear() && date.getMonth() === thisMonth.getMonth(); }).length, icon: CircleCheck, note: '每一份帮助都算数' }];
 return <main className="page-shell inner-page"><div className="business-heading"><div className="page-intro mb-0"><div className="eyebrow"><Store size={15}/>青禾咖啡 · 大学城店</div><h1>商家工作台</h1><p>周末的得力帮手，从这里找到。</p></div><Button asChild><Link href="/business/publish"><Plus size={17}/>发布兼职</Link></Button></div><div className="stat-grid">{stats.map(({label,value,icon: Icon,note}) => <div className="panel stat-card" key={label}><span>{label}</span><Icon/><b>{ready ? value : '—'}</b><small>{note}</small></div>)}</div><div className="account-hint">当前为青禾咖啡商家演示身份。可审核示例同学的报名；报名青禾的兼职后，也可以在这里体验「学生报名 → 商家确认」的完整流程。</div><div className="dashboard-section-title"><h2>我的兼职</h2><span>共 {mine.length} 个发布</span></div>{!ready ? <div className="loading-state">正在加载工作台…</div> : mine.map(job => { const applicants = relevant.filter(a => a.jobId === job.id); return <article className="panel business-job" key={job.id}><div className="business-job-row"><JobLogo job={job}/><div className="business-job-info"><Link href={`/jobs/${job.id}`}><h3>{job.title}</h3></Link><p><span className="text-[#df8550]">¥{job.salary}/小时</span><span>{dateLabel(job.date)}</span><span>报名 {applicantCount(job)} / 招 {job.recruitCount} 人</span></p></div><div className="business-job-actions"><Button variant="outline" size="sm" asChild><Link href={`/business/edit/${job.id}`}><Pencil size={13}/>编辑</Link></Button><Button size="sm" variant={expanded === job.id ? 'secondary' : 'default'} onClick={() => setExpanded(expanded === job.id ? null : job.id)} aria-expanded={expanded === job.id}>查看报名{expanded === job.id ? <ChevronUp size={14}/> : <ChevronDown size={14}/>}</Button></div></div>{expanded === job.id && <div className="applicants"><h4>已确认 {applicants.filter(a => ['confirmed','completed'].includes(a.status)).length} 人 · 剩余 {remaining(job)} 个名额</h4>{applicants.length ? applicants.map(a => <div className="applicant" key={a.id}><div className="applicant-avatar">{a.studentName[0]}</div><div><b>{a.studentName}</b><p>{a.major}</p></div><div className="applicant-actions"><Badge className={`status-${a.status}`}>{statusLabels[a.status]}</Badge>{a.status === 'pending' && <><Button variant="ghost" size="sm" onClick={() => updateApplication(a.id,'rejected')}>不通过</Button><Button size="sm" disabled={remaining(job) === 0} onClick={() => updateApplication(a.id,'confirmed')}>确认报名</Button></>}{a.status === 'confirmed' && <Button size="sm" variant="outline" onClick={() => updateApplication(a.id,'completed')}>标记完成</Button>}</div></div>) : <p className="form-footnote">还没有同学报名，发布的信息已在找兼职页面展示。</p>}</div>}</article>; })}</main>;
}
