'use client';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Clock3, MapPin, Star, Users, ShieldCheck, CheckCircle2, Wallet } from 'lucide-react';
import { useApp } from '@/lib/store';
import { STUDENT_ID } from '@/lib/data';
import { dateLabel, hours, income } from '@/lib/utils';
import { JobLogo } from '@/components/job-card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
export default function JobDetail() {
 const { id } = useParams<{ id: string }>(); const { jobs, applications, apply, ready, remaining } = useApp(); const [success, setSuccess] = useState(false);
 const job = jobs.find(j => j.id === id); const applied = applications.some(a => a.jobId === id && a.studentId === STUDENT_ID);
 if (!ready) return <main className="page-shell loading-state">正在加载兼职信息…</main>;
 if (!job) return <main className="page-shell empty-state"><h1>这份兼职暂时找不到了</h1><Button asChild><Link href="/">返回找兼职</Link></Button></main>;
 return <main className="page-shell inner-page"><Link className="back-link" href="/#discover"><ArrowLeft size={16}/>返回兼职列表</Link><div className="detail-grid"><div><section className="panel detail-header"><div className="detail-brand"><JobLogo job={job} large/><div><Badge>{job.category}</Badge><h1>{job.title}</h1><p>{job.business}</p></div></div><div className="detail-salary salary"><span className="currency">¥</span>{job.salary}<span className="salary-unit">/ 小时</span><Badge className="neutral-badge">按时计薪</Badge></div><div className="detail-facts"><div><CalendarDays/><span>工作日期<b>{dateLabel(job.date)}</b></span></div><div><Clock3/><span>工作时间<b>{job.startTime}–{job.endTime} · {hours(job.startTime,job.endTime)} 小时</b></span></div><div><MapPin/><span>工作地点<b>{job.location}</b><small>距学校 {job.distance} km</small></span></div><div><Users/><span>招聘人数<b>招 {job.recruitCount} 人 · 还需 {remaining(job)} 人</b></span></div></div></section><section className="panel detail-content"><h2>这份兼职做什么？</h2><ol>{job.description.map((line,i) => <li key={line}><span>{String(i+1).padStart(2,'0')}</span>{line}</li>)}</ol><h2>希望你是这样的</h2><ul>{job.requirements.map(line => <li key={line}><CheckCircle2 size={17}/>{line}</li>)}</ul></section><div className="safety-note"><ShieldCheck size={23}/><div><b>安心兼职小提醒</b><p>请通过平台确认工作安排。拒绝押金、培训费和任何提前转账要求，个人证件请妥善保管。</p></div></div></div><aside><section className="panel income-panel"><div className="income-label"><Wallet size={19}/>这个周末，预计收获</div><div className="income-total"><span>¥</span>{income(job.salary,job.startTime,job.endTime)}</div><p>{hours(job.startTime,job.endTime)} 小时 × ¥{job.salary}/小时</p><div className="income-divider"/><div className="income-tip"><CheckCircle2 size={16}/>时薪清晰，认真付出有回报</div><Button size="lg" className="w-full" disabled={!ready || (!applied && remaining(job) === 0)} onClick={() => { if (apply(job.id)) setSuccess(true); }}>{applied ? '已报名 · 查看报名提示' : remaining(job) === 0 ? '本次招聘已满' : '立即报名'}<ArrowRight size={18}/></Button>{applied && <Link className="center-link" href="/applications">前往我的报名 →</Link>}<small>报名后由商家确认，请留意报名状态</small></section><section className="panel business-panel"><div className="business-avatar">{job.business.slice(0,1)}</div><h3>{job.business}</h3><div className="business-stats"><div><b><Star size={15} fill="currentColor"/>{job.rating}</b><span>商家评分</span></div><div><b>{job.historyCount}</b><span>历史兼职</span></div></div><p>大学城周边 · 本地商家</p></section></aside></div>{success && <div className="success-inline" role="status"><CheckCircle2/><div><b>报名成功，期待你的新收获！</b><p>商家正在等待审核，你可以在「我的报名」查看进度。</p></div><Button asChild><Link href="/applications">查看我的报名<ArrowRight size={16}/></Link></Button><button className="text-button" onClick={() => setSuccess(false)}>收起</button></div>}</main>;
}
